"""allow

Revision ID: 38fe9ef57fc4
Revises: 3e02b2a9571e
Create Date: 2023-08-17 15:05:35.969050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38fe9ef57fc4"
down_revision = "3e02b2a9571e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
