"""add_tx_table

Revision ID: 3e02b2a9571e
Revises: 
Create Date: 2023-08-17 11:25:24.180946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e02b2a9571e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column("nonce", sa.Integer(), nullable=True),
        sa.Column("block_hash", sa.String(), nullable=True),
        sa.Column("block_number", sa.Integer(), nullable=True),
        sa.Column("transaction_index", sa.Integer(), nullable=True),
        sa.Column("from_address", sa.String(), nullable=True),
        sa.Column("to_address", sa.String(), nullable=True),
        sa.Column("value", sa.Numeric(), nullable=True),
        sa.Column("gas", sa.BigInteger(), nullable=True),
        sa.Column("gas_price", sa.Numeric(), nullable=True),
        sa.Column("block_timestamp", sa.DateTime(), nullable=True),
        sa.Column("max_fee_per_gas", sa.Numeric(), nullable=True),
        sa.Column("max_priority_fee_per_gas", sa.Numeric(), nullable=True),
        sa.Column("transaction_type", sa.String(), nullable=True),
        sa.Column("receipts_cumulative_gas_used", sa.BigInteger(), nullable=True),
        sa.Column("receipts_gas_used", sa.BigInteger(), nullable=True),
        sa.Column("receipts_contract_address", sa.String(), nullable=True),
        sa.Column("receipts_root", sa.String(), nullable=True),
        sa.Column("receipts_status", sa.Boolean(), nullable=True),
        sa.Column("receipts_effective_gas_price", sa.Numeric(), nullable=True),
        sa.Column("gas_used_gwei", sa.Numeric(), nullable=True),
        sa.Column("gas_used_usd", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("transactions_pkey")),
    )
    op.create_index(
        op.f("transactions_block_hash_idx"),
        "transactions",
        ["block_hash"],
        unique=False,
    )
    op.create_index(
        op.f("transactions_hash_idx"), "transactions", ["hash"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("transactions_hash_idx"), table_name="transactions")
    op.drop_index(op.f("transactions_block_hash_idx"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
